tests left
Neitsch/ASE4156 pull request #160
Opened 2017-11-12 19:33 UTC by jomivega

2017-11-12 19:41 UTC, jomivega commented
Thats a first! I passed travis on the first commit 😃😃

2017-11-12 19:55 UTC, Neitsch reviewed
Overall, really good tests. Just small suggestions :)

2017-11-12 19:55 UTC, Neitsch commented on tests/test_trading_model.py
> +    user = create_user()
Good idea! To optimize this, please use a fixture:
```
@pytest.fixture
def user():
    pwd = ''.join(random.choices(string.ascii_uppercase + string.digits, k=9))
     user = User.objects.create(username='user', password=pwd)
     return user

def test_trading_acc_av_stk(user):
```

2017-11-12 19:55 UTC, Neitsch commented on tests/test_trading_model.py
> +    account = create_account()
Here you can also use a fixture

2017-11-12 19:55 UTC, Neitsch commented on tests/test_trading_model.py
> +    assert current_value == -value_of_stock1
Preferrrable quantity != 1 to verify that the quantity is considered.

2017-11-12 19:55 UTC, Neitsch commented on tests/test_trading_model.py
> +    account.save()
Use a fixture

2017-11-12 19:55 UTC, Neitsch commented on tests/test_stocks_model.py
> +        )
Same here, quantity != 1 is preferred.

2017-11-13 05:03 UTC, Neitsch requested changes
plz address comments

2017-11-13 16:25 UTC, Neitsch approved these changes

2017-11-13 16:30 UTC, merged